{% set sanitized_branch = (branch or "dev").replace('/', '-') %}

name: stream
namespace: datawire

profiles:
  stable:
    endpoint: /stream/
    max_memory: 0.1G
    max_cpu: 0.1
  default:
    name: {{sanitized_branch}}
    endpoint: /{{sanitized_branch}}/stream/
    max_memory: 0.1G
    max_cpu: 0.1
  canary:
    endpoint: /stream/
    max_memory: 0.1G
    max_cpu: 0.1
    weight: 50
  shadow:
    endpoint: /stream/
    max_memory: 0.1G
    max_cpu: 0.1
    shadow: true

branches:
  master: stable
  dev/*: default
